"""
Webhook Model
Stores registered webhook endpoints for server-to-server event delivery.
"""
import uuid

from sqlalchemy import Column, String, Boolean, DateTime, Integer, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func

from app.db.database import Base

# Supported event types clients may subscribe to
WEBHOOK_EVENTS = [
    "schema.enrichment.complete",
    "schema.enrichment.failed",
]


class Webhook(Base):
    """
    A registered URL that Vernql will POST to when subscribed events occur.

    Delivery uses HMAC-SHA256 signing via the X-Vernql-Signature header so
    the receiving server can verify the payload came from Vernql.
    """
    __tablename__ = "webhooks"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    company_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Target URL (validated as HTTPS in service layer)
    url = Column(String(2048), nullable=False)

    # JSON array of subscribed event names, e.g. ["schema.enrichment.complete"]
    events = Column(JSONB, nullable=False, default=list)

    # HMAC signing secret stored as plain text (generated by us, shown once).
    # In a future iteration this should be encrypted at rest.
    signing_secret = Column(String(128), nullable=True)

    is_active = Column(Boolean, default=True, nullable=False, index=True)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Delivery metadata — updated after each attempt
    last_triggered_at  = Column(DateTime(timezone=True), nullable=True)
    last_status_code   = Column(Integer, nullable=True)   # HTTP status of last delivery

    __table_args__ = (
        Index("ix_webhooks_company_active", "company_id", "is_active"),
    )

    def __repr__(self) -> str:
        return f"<Webhook(id={self.id}, url={self.url}, company={self.company_id})>"
