"""
Query Generation Endpoints
"""
from typing import List, Optional
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from datetime import datetime

from app.db.database import get_db
from app.core.dependencies import CurrentCompany
from app.services.sql_generator import SQLGenerator
from app.models import Query, QueryStatus

router = APIRouter(prefix="/queries", tags=["Queries"])


# Pydantic schemas
class QueryRequest(BaseModel):
    """Request schema for generating SQL from natural language"""
    schema_id: UUID = Field(..., description="UUID of the schema to query against")
    query: str = Field(..., description="Natural language query", min_length=1, max_length=1000)


class QueryResponse(BaseModel):
    """Response schema for generated query"""
    id: UUID
    natural_language_query: str
    generated_sql: str
    confidence_score: float
    warnings: List[str] = []
    ai_provider: str
    ai_model: str
    created_at: str

    class Config:
        from_attributes = True


class QueryHistoryResponse(BaseModel):
    """Response schema for query history"""
    queries: List[QueryResponse]
    total: int


@router.post(
    "",
    response_model=QueryResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate SQL from natural language"
)
async def generate_query(
    query_data: QueryRequest,
    company: CurrentCompany,
    db: Session = Depends(get_db)
):
    """
    Generate SQL query from natural language

    Uses AI with enriched schema context to convert natural language
    into accurate, safe SQL queries.

    ## Examples

    **Simple query:**
    ```
    "Show me all active users"
    ```

    **Aggregation:**
    ```
    "How many orders were placed last month?"
    ```

    **Join query:**
    ```
    "List customers who have placed orders over $1000"
    ```

    **Sorting:**
    ```
    "Top 10 best-selling products"
    ```

    ## Parameters
    - **schema_id**: UUID of the database schema to query
    - **query**: Natural language question about the data

    ## Response
    Returns:
    - Generated SQL query
    - Confidence score (0.0-1.0)
    - Warnings (if any)
    - Query saved to history for analytics
    """
    try:
        # Generate SQL
        generator = SQLGenerator()
        result = await generator.generate_sql(
            db=db,
            schema_id=str(query_data.schema_id),
            natural_language_query=query_data.query,
            company_id=str(company.id)
        )

        # Store in history
        query_record = await generator.store_query_result(
            db=db,
            company_id=str(company.id),
            schema_id=str(query_data.schema_id),
            natural_language_query=query_data.query,
            generated_sql=result.sql,
            confidence=result.confidence,
            status=QueryStatus.SUCCESS
        )

        return QueryResponse(
            id=query_record.id,
            natural_language_query=query_record.natural_language_query,
            generated_sql=query_record.generated_sql,
            confidence_score=query_record.confidence_score,
            warnings=result.warnings,
            ai_provider=query_record.ai_provider,
            ai_model=query_record.ai_model,
            created_at=query_record.created_at.isoformat()
        )

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate SQL: {str(e)}"
        )


@router.get(
    "",
    response_model=QueryHistoryResponse,
    summary="Get query history"
)
async def get_query_history(
    company: CurrentCompany,
    db: Session = Depends(get_db),
    schema_id: Optional[UUID] = None,
    limit: int = 50
):
    """
    Get query generation history

    Returns recent queries generated by your company, ordered by most recent first.

    ## Parameters
    - **schema_id**: Optional - filter by specific schema
    - **limit**: Maximum number of queries to return (default: 50, max: 100)

    ## Response
    Returns list of generated queries with SQL and metadata
    """
    # Validate limit
    limit = min(limit, 100)

    # Build query
    query = db.query(Query).filter(Query.company_id == company.id)

    if schema_id:
        query = query.filter(Query.schema_id == schema_id)

    # Get queries ordered by most recent
    queries = query.order_by(Query.created_at.desc()).limit(limit).all()

    # Build response
    query_responses = [
        QueryResponse(
            id=q.id,
            natural_language_query=q.natural_language_query,
            generated_sql=q.generated_sql,
            confidence_score=q.confidence_score or 0.0,
            warnings=[],  # Warnings not stored in DB
            ai_provider=q.ai_provider or "unknown",
            ai_model=q.ai_model or "unknown",
            created_at=q.created_at.isoformat()
        )
        for q in queries
    ]

    return QueryHistoryResponse(
        queries=query_responses,
        total=len(query_responses)
    )


@router.get(
    "/{query_id}",
    response_model=QueryResponse,
    summary="Get query by ID"
)
async def get_query(
    query_id: UUID,
    company: CurrentCompany,
    db: Session = Depends(get_db)
):
    """
    Get a specific query by ID

    ## Parameters
    - **query_id**: UUID of the query

    ## Response
    Returns the query with generated SQL and metadata
    """
    query = db.query(Query).filter(
        Query.id == query_id,
        Query.company_id == company.id
    ).first()

    if not query:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Query not found"
        )

    return QueryResponse(
        id=query.id,
        natural_language_query=query.natural_language_query,
        generated_sql=query.generated_sql,
        confidence_score=query.confidence_score or 0.0,
        warnings=[],
        ai_provider=query.ai_provider or "unknown",
        ai_model=query.ai_model or "unknown",
        created_at=query.created_at.isoformat()
    )


class QueryFeedbackRequest(BaseModel):
    """Request schema for query feedback/validation"""
    is_helpful: bool = Field(..., description="Whether the generated SQL was helpful")
    is_correct: bool = Field(..., description="Whether the generated SQL was correct")
    feedback_notes: Optional[str] = Field(None, description="Optional feedback notes", max_length=1000)


class QueryFeedbackResponse(BaseModel):
    """Response schema for feedback submission"""
    query_id: UUID
    feedback_recorded: bool
    message: str


@router.post(
    "/{query_id}/feedback",
    response_model=QueryFeedbackResponse,
    summary="Provide feedback on generated query"
)
async def submit_query_feedback(
    query_id: UUID,
    feedback: QueryFeedbackRequest,
    company: CurrentCompany,
    db: Session = Depends(get_db)
):
    """
    Submit feedback/validation for a generated query

    Allows users to indicate whether the generated SQL was helpful and correct.
    This feedback is used to improve the system over time.

    ## Parameters
    - **query_id**: UUID of the query to provide feedback on
    - **is_helpful**: Whether the query was helpful to the user
    - **is_correct**: Whether the generated SQL was accurate
    - **feedback_notes**: Optional notes about the query

    ## Response
    Returns confirmation that feedback was recorded

    ## Use Cases
    - Mark successful queries for future training
    - Report incorrect SQL generation
    - Provide additional context for improvement
    """
    # Verify query exists and belongs to company
    query = db.query(Query).filter(
        Query.id == query_id,
        Query.company_id == company.id
    ).first()

    if not query:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Query not found"
        )

    # Store feedback in query_metadata JSON field
    if query.query_metadata is None:
        query.query_metadata = {}

    query.query_metadata["feedback"] = {
        "is_helpful": feedback.is_helpful,
        "is_correct": feedback.is_correct,
        "feedback_notes": feedback.feedback_notes,
        "submitted_at": datetime.utcnow().isoformat()
    }

    # Update status based on feedback
    if feedback.is_correct and feedback.is_helpful:
        query.status = QueryStatus.SUCCESS
    elif not feedback.is_correct:
        query.status = QueryStatus.FAILED

    db.commit()

    # If feedback is positive, consider creating an example
    if feedback.is_helpful and feedback.is_correct and query.confidence_score >= 0.8:
        from app.services.example_manager import ExampleManager
        from app.models import ExampleSource

        example_manager = ExampleManager()
        example_manager.create_example(
            db=db,
            company_id=str(company.id),
            schema_id=str(query.schema_id),
            natural_language=query.natural_language_query,
            sql_query=query.generated_sql,
            source=ExampleSource.USER_FEEDBACK,
            quality_score=10,  # User-verified examples get high score
            is_verified=True
        )

    return QueryFeedbackResponse(
        query_id=query.id,
        feedback_recorded=True,
        message="Thank you for your feedback! This helps improve our SQL generation."
    )


@router.post(
    "/validate",
    response_model=QueryFeedbackResponse,
    summary="Validate a query (alias for feedback)",
    deprecated=True
)
async def validate_query(
    query_id: UUID,
    company: CurrentCompany,
    db: Session = Depends(get_db),
    is_helpful: bool = True,
    is_correct: bool = True
):
    """
    Validate a generated query (legacy endpoint)

    **Deprecated:** Use POST /v1/queries/{query_id}/feedback instead

    This endpoint is maintained for backward compatibility.
    """
    feedback = QueryFeedbackRequest(
        is_helpful=is_helpful,
        is_correct=is_correct
    )

    return await submit_query_feedback(
        query_id=query_id,
        feedback=feedback,
        company=company,
        db=db
    )
