"""add query_examples table

Revision ID: 3e273f53d55f
Revises: 06c8ee5caf69
Create Date: 2026-03-18 02:40:06.816426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e273f53d55f'
down_revision = '06c8ee5caf69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('natural_language', sa.Text(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AUTO_GENERATED', 'USER_FEEDBACK', 'CURATED', name='examplesource'), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_examples_company_id'), 'query_examples', ['company_id'], unique=False)
    op.create_index(op.f('ix_query_examples_schema_id'), 'query_examples', ['schema_id'], unique=False)
    op.create_unique_constraint(None, 'api_keys', ['id'])
    op.create_unique_constraint(None, 'companies', ['id'])
    op.create_unique_constraint(None, 'queries', ['id'])
    op.create_unique_constraint(None, 'schema_columns', ['id'])
    op.create_unique_constraint(None, 'schema_tables', ['id'])
    op.create_unique_constraint(None, 'schemas', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schemas', type_='unique')
    op.drop_constraint(None, 'schema_tables', type_='unique')
    op.drop_constraint(None, 'schema_columns', type_='unique')
    op.drop_constraint(None, 'queries', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_index(op.f('ix_query_examples_schema_id'), table_name='query_examples')
    op.drop_index(op.f('ix_query_examples_company_id'), table_name='query_examples')
    op.drop_table('query_examples')
    # ### end Alembic commands ###
