"""Initial schema - companies, api_keys, schemas, queries

Revision ID: 06c8ee5caf69
Revises: 
Create Date: 2026-03-14 01:19:32.993632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06c8ee5caf69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_api_keys_company_active', 'api_keys', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_company_id'), 'api_keys', ['company_id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.Enum('POSTGRESQL', 'MYSQL', name='databasetype', native_enum=False), nullable=False),
    sa.Column('enriched_description', sa.Text(), nullable=True),
    sa.Column('raw_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_schemas_company_active', 'schemas', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_schemas_company_id'), 'schemas', ['company_id'], unique=False)
    op.create_index('ix_schemas_company_name', 'schemas', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_schemas_is_active'), 'schemas', ['is_active'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('natural_language_query', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'TIMEOUT', name='querystatus', native_enum=False), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('query_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_queries_company_created', 'queries', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_queries_company_id'), 'queries', ['company_id'], unique=False)
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index('ix_queries_schema_created', 'queries', ['schema_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_queries_schema_id'), 'queries', ['schema_id'], unique=False)
    op.create_index('ix_queries_status', 'queries', ['status'], unique=False)
    op.create_table('schema_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enriched_description', sa.Text(), nullable=True),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_schema_tables_schema_id'), 'schema_tables', ['schema_id'], unique=False)
    op.create_index('ix_schema_tables_schema_name', 'schema_tables', ['schema_id', 'name'], unique=False)
    op.create_table('schema_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('foreign_key_table', sa.String(length=255), nullable=True),
    sa.Column('foreign_key_column', sa.String(length=255), nullable=True),
    sa.Column('enriched_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['schema_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_schema_columns_table_id'), 'schema_columns', ['table_id'], unique=False)
    op.create_index('ix_schema_columns_table_name', 'schema_columns', ['table_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schema_columns_table_name', table_name='schema_columns')
    op.drop_index(op.f('ix_schema_columns_table_id'), table_name='schema_columns')
    op.drop_table('schema_columns')
    op.drop_index('ix_schema_tables_schema_name', table_name='schema_tables')
    op.drop_index(op.f('ix_schema_tables_schema_id'), table_name='schema_tables')
    op.drop_table('schema_tables')
    op.drop_index('ix_queries_status', table_name='queries')
    op.drop_index(op.f('ix_queries_schema_id'), table_name='queries')
    op.drop_index('ix_queries_schema_created', table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_index(op.f('ix_queries_company_id'), table_name='queries')
    op.drop_index('ix_queries_company_created', table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_schemas_is_active'), table_name='schemas')
    op.drop_index('ix_schemas_company_name', table_name='schemas')
    op.drop_index(op.f('ix_schemas_company_id'), table_name='schemas')
    op.drop_index('ix_schemas_company_active', table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_company_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_company_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
